### ISSUE TITLE
ESLint breaks on freshly cloned repository

### ISSUE THREAD

**Issue by kamilogorek** [cyclejs/core#252]
# Steps to reproduce

```sh
$ npm clone https://github.com/cyclejs/dom.git
$ cd dom
$ npm i
$ npm run eslint
```

# Environment

```
$ node -v // node v5.7.0
$ npm -v // npm v3.6.0
$ osx -v /// osx v10.11.2
```

# Results

```sh
~/Projects/javascript/cyclejs/dom:master$ npm run test

> @cycle/dom@9.1.0 test /Users/kamilogorek/Projects/javascript/cyclejs/dom
> npm run eslint && npm run test-node && npm run test-browser


> @cycle/dom@9.1.0 eslint /Users/kamilogorek/Projects/javascript/cyclejs/dom
> eslint src/

/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/estraverse/estraverse.js:517
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type RestElement.
    at Controller.traverse (/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/estraverse/estraverse.js:517:31)
    at EventEmitter.module.exports.api.verify (/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/eslint.js:787:24)
    at processText (/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/cli-engine.js:199:27)
    at processFile (/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/cli-engine.js:224:12)
    at /Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/cli-engine.js:320:26
    at /Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/util/traverse.js:85:9)
    at /Users/kamilogorek/Projects/javascript/cyclejs/dom/node_modules/eslint/lib/util/traverse.js:104:9
```

**Comment by kamilogorek** [comment]
Update: same thing happens for `http`. `isolate` and `core` work just fine.

**Comment by kamilogorek** [comment]
Update: errors are caused by spread and default params operators eg.

```js
return Rx.Observable
  .combineLatest(vtree.children.map(transposeVTree), (...arr) =>
    (...)
  )
```

and

```js
function makeHTTPDriver({eager = false} = {eager: false}) {
  (...)
}
```

**Comment by kamilogorek** [comment]
@staltz what would you say about migrating most of cycle.js repositories to eslint v2.0.0?

**Comment by TylorS** [comment]
This needs to be merged first - https://github.com/cyclejs/eslint-plugin-cycle/pull/1

**Comment by kamilogorek** [comment]
That's right. And https://github.com/cyclejs/eslint-config-cycle/pull/5/ as well.

**Comment by TylorS** [comment]
I believe I can merge, but I don't have the ability to release updates. @staltz Will have to follow through with those.

**Comment by iambumblehead** [comment]
This issue affects me here btw https://github.com/cyclejs/http/pull/48

**Comment by staltz** [comment]
Fixed (or at least the reproduction steps given at the beginning are no long causing the bug to happen). Thanks folks for contributing, and sorry for delays

**Comment by iambumblehead** [comment]
I've cloned the latest version 8.2.2 and still see this error when using `npm run test`

**Comment by psychowico** [comment]
this isn't looking to be fixed. fresh copy of `cycle/dom` still have same issue just after fresh copy `npm install`

**Comment by staltz** [comment]
We are very close to publishing the new version of Cycle DOM, v10, and this issue won't be relevant anymore. In the meantime, we can just ignore these lint errors.
